spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanikumari.gulla3@gmail.com
    password: ktxy cloa mvic wwzo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 8080
